sudo: false

language: node_js

node_js:
  - "0.10.45"

before_install:
  - "curl https://install.meteor.com/ | sh"
rvm: 
  - 2.2
  - jruby
env:
  - USE_NETWORK=true CAMPFIRE_TOKEN=abc123 TIMEOUT=1000
  - USE_NETWORK=false CAMPFIRE_TOKEN=abc123 TIMEOUT=1000
